### ISSUE TITLE
Create a settings model with title

### ISSUE THREAD

**Issue by davydovanton** [hanami/contributors#44]
## What we want
In general, I want to make this project, not hanami specific. That's why it will be great to set up the title on index page with a title from settings:
![screenshot 2018-02-11 14 36 52](https://user-images.githubusercontent.com/1147484/36072933-331f1d2c-0f39-11e8-8d39-7d0ca2a7cdda.jpeg)

## TODO
_Please make 1 PR for each point from this list_ ❤️

- [x] Create a new model `settings` with title field
- [x] Create a show page on admin app with current values
- [x] Add ability for editing setting (only `title` now)
- [x] Use `settings.title` instead `"Hanami contributors"`

## Questions
I have only one question: how we will work with settings. I think it will be better if on update we will create a new record in DB with new values. And works only with a latest created settings object in a web app. Because in this case, we can create "history log" for all settings changes in the project. WDYT?

**Comment by davydovanton** [comment]
@GustavoCaso do you want to help with it? 😊

**Comment by GustavoCaso** [comment]
@davydovanton I would love to.

**Comment by suryakun** [comment]
Hi guys, may I try to solve this issue?

**Comment by GustavoCaso** [comment]
@suryakun I'm working on it. If you're really interested in doing it I can stop my work and left it to you

**Comment by GustavoCaso** [comment]
@suryakun I'm sure @davydovanton have other ideas you could work on

**Comment by suryakun** [comment]
@GustavoCaso alright then, you can keep going. @davydovanton do you have any other one? beginner level one please..

**Comment by davydovanton** [comment]
@suryakun hey, thanks for your help! I updated this issue, could you check it? https://github.com/hanami/contributors/issues/20

**Comment by suryakun** [comment]
Got it

**Comment by davydovanton** [comment]
Awesome work @GustavoCaso ❤️
